#!/usr/bin/env bash

set -f
set -o pipefail
set -o errexit
set -o nounset

ec2_script="$(dirname $(realpath $0) )/ec2"

function get_instance_ip_from_input () {
  if [[ "$#" -ge 1 ]] && [[ -n "$1" ]] && [[ "$1" =~ ^[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*$ ]];then
    instance_ip="$1"
  elif [[ "$#" -ge 1 ]] && [[ -n "$1" ]];then
    instance_ip="$( $ec2_script details $1 \
      | jq -r -M '.Reservations[]|.Instances[0]|.PublicIpAddress'
    )"
  else
    local instanceid="$( $ec2_script list \
      | jq -r -M 'map(select(.state=="running"))[0].InstanceId?//empty'
    )"
    if [[ -z "$instanceid" ]];then
      unset instanceid
    fi
    instance_ip="$( $ec2_script details $instanceid \
      | jq -r -M '.Reservations[]|.Instances[0]|.PublicIpAddress'
    )"
  fi
}

get_instance_ip_from_input $@
echo "$instance_ip"


