#!/usr/bin/env bash

set -f
set -o pipefail
set -o errexit
set -o nounset

ec2_script="$(dirname $(realpath $0) )/ec2"

function get_instance_ip_from_input () {
  if [[ "$#" -ge 1 ]] && [[ "$1" =~ ^[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*$ ]];then
    instance_ip="$1"

  elif [[ "$#" -ge 1 ]] && [[ "$1" =~ ^i-[0-9a-f]*$ ]];then
    instance_ip="$( $ec2_script details $1 \
      | jq -r -M '.Reservations[]|.Instances[0]|.PublicIpAddress'
    )"

  elif [[ "$#" -ge 1 ]];then
    instance_ip="$($ec2_script -l list \
      | jq -r "\
.Reservations|\
map(select(.Instances[0].Tags//[]|contains([{Value:\"$1\"}])))\
|.[0].Instances[0].PublicIpAddress"
    )"

  else
    instance_ip="$($ec2_script list running | jq -r '.[0].PublicIpAddress')"
  fi
}

get_instance_ip_from_input $@
echo "$instance_ip"

